default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_development

production:
  <<: *default
  username: <%= ENV["username"] %>
  password: <%= ENV["password"] %>
  database: <%= ENV["database"] %>
  host: <%= ENV["host"] %>
  port: 5432